spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        id :
          new_generator_mappings : false
        format_sql: true
        ddl-auto: create-drop



logging:
  level:
    root: trace


